export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  COMPANY_VIEW: 'company.view',
  COMPANY_CREATE: 'company.create',
  COMPANY_EDIT: 'company.edit',
  COMPANY_DELETE: 'company.delete',
  ROLE_VIEW: 'role.view',
  ROLE_CREATE: 'role.create',
  ROLE_EDIT: 'role.edit',
  ROLE_DELETE: 'role.delete',
  ROLE_CLAIM_VIEW: 'roleclaim.view',
  ROLE_CLAIM_CREATE: 'roleclaim.create',
  ROLE_CLAIM_EDIT: 'roleclaim.edit',
  ROLE_CLAIM_DELETE: 'roleclaim.delete',
  ROLE_MAPPING_VIEW: 'rolemapping.view',
  ROLE_MAPPING_CREATE: 'rolemapping.create',
  ROLE_MAPPING_EDIT: 'rolemapping.edit',
  ROLE_MAPPING_DELETE: 'rolemapping.delete',
  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_EDIT: 'user.edit',
  USER_DELETE: 'user.delete',
  BRANCH_MASTER_VIEW: 'branchmaster.view',
  CITY_MASTER_VIEW: 'citymaster.view',
  COUNTRY_MASTER_VIEW: 'countrymaster.view',
  TAX_MASTER_VIEW: 'taxmaster.view',
  AREA_MASTER_VIEW: 'areamaster.view',
  TABLE_MASTER_VIEW: 'tablemaster.view',
  WAITER_MASTER_VIEW: 'waitermaster.view',
  POS_ORDER_SCREEN_VIEW: 'posorderscreen.view',
  WELCOME_VIEW: 'welcome.view',
}

export const ALL_PERMISSIONS = Object.values(PERMISSIONS)
